### ISSUE TITLE
I got this error build on macOS Sierra

### ISSUE THREAD

**Issue by Synizter** [ryanfb/pcl-tools#5]
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0:`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -DDISABLE_OPENNI -DEIGEN_USE_NEW_STDVECTOR -DEIGEN_YES_I_KNOW_SPARSE_MODULE_IS_NOT_STABLE_YET -DFLANN_STATIC -DvtkDomainsChemistry_AUTOINIT="1(vtkDomainsChemistryOpenGL2)" -DvtkRenderingContext2D_AUTOINIT="1(vtkRenderingContextOpenGL2)" -DvtkRenderingCore_AUTOINIT="3(vtkInteractionStyle,vtkRenderingFreeType,vtkRenderingOpenGL2)" -DvtkRenderingFreeType_AUTOINIT="1(vtkRenderingFreeTypeFontConfig)" -DvtkRenderingVolume_AUTOINIT="1(vtkRenderingVolumeOpenGL2)" -I/usr/local/Cellar/vtk/7.0.0_4/include/vtk-7.0 -I/usr/local/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/hdf5/1.8.17/include -I/usr/local/opt/szip/include -I/usr/include/libxml2 -I/usr/local/include/pcl-1.6 -I/usr/local/Cellar/eigen/3.2.10/include/eigen3 -I/usr/local/Cellar/flann/1.9.1_1/include  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk   -DDISABLE_LIBUSB-1.0 vtkDomainsChemistry_AUTOINIT=1(vtkDomainsChemistryOpenGL2) vtkRenderingContext2D_AUTOINIT=1(vtkRenderingContextOpenGL2) vtkRenderingCore_AUTOINIT=3(vtkInteractionStyle,vtkRenderingFreeType,vtkRenderingOpenGL2) vtkRenderingFreeType_AUTOINIT=1(vtkRenderingFreeTypeFontConfig) vtkRenderingVolume_AUTOINIT=1(vtkRenderingVolumeOpenGL2)  -msse4.1 -mfpmath=sse -o CMakeFiles/PCDViewer.dir/src/pcd_viewer.cpp.o -c /Users/Goragod/pcl-tools-master/src/pcd_viewer.cpp'
make[2]: **\* [CMakeFiles/PCDViewer.dir/src/pcd_viewer.cpp.o] Error 2
make[1]: **\* [CMakeFiles/PCDViewer.dir/all] Error 2
make: **\* [all] Error 2

**Comment by sebinefrancis** [comment]
I have built it successfully in Ubuntu 20.04 with boost version "1.71.0", with minor modifications in two files:

1. I got error regarding boost::thread::sleep. It turned out to be issue with the old and new boost library versions. I found solution from : https://stackoverflow.com/a/4265343/6394769  So I made changes in **pcd_viewer.cpp**. Changed 
'`boost::this_thread::sleep`' to '`boost::this_thread::sleep_for`' and added 
```
#include <boost/chrono.hpp>
#include <boost/thread/thread.hpp>
``` because my version of boost was newer.

2. Then I got some error 'undefined reference to symbol 'pthread_condattr_setclock@@GLIBC_2.3.3''. To solve this I had to edit **CMakeLists.txt** and add `thread` to this line after system like this: `find_package(Boost COMPONENTS REQUIRED system  thread )`

After these changes it built successfully. Hope this helps someone.

**Comment by ryanfb** [comment]
Thanks! I've updated the `CMakeLists.txt` and updated the upstream tools so they should compile now.
